### ISSUE TITLE
What do i install this on?

### ISSUE THREAD

**Issue by sebscamcoder** [RbKomar/AHHunter#2]
Hello!
I am having trouble finding where to do the $ pip install thingy.
Can I have some help?

**Comment by RbKomar** [comment]
Hello there,
Since I just shared the script, firstly u need to download the Python 3+ to run it. The pip is the python manager that allows your python script to use additional libraries. https://www.youtube.com/watch?v=Ko9b_vC6XY0 <-- this video is a nice explanation of how to use and install pip. Once you will have your environment set,  just download the packages I pointed in the readme file.
